services:
  keycloak:
    container_name: keycloak
    build: keycloak
    restart: unless-stopped
    ports:
      - "8180:8080"
      - "9000:9000"
    env_file:
      - keycloak.env

  keycloak-healthcheck:
    container_name: keycloak-healthcheck
    build: keycloak-healthcheck
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_ADMIN_HOST=http://keycloak:9000
      - RETRY_MAX_ATTEMPT=10
      - RETRY_WAIT_INTERVAL_SECONDS=5

  keycloak-init:
    container_name: keycloak-init
    build: keycloak-init
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    env_file:
      - keycloak.env
    environment:
      - KEYCLOAK_HOST=http://keycloak:8080

  identity-service:
    container_name: identity-app
    build: identity-app
    restart: always
    ports:
      - "8181:8181"
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - KEYCLOAK_SERVERURL=http://keycloak:8080
      - KEYCLOAK_REALM=shopping-api
      - KEYCLOAK_CLIENTID=demo-client
      - KEYCLOAK_CLIENTSECRET=ZhVCiZ3pyKwxWcXh5K7wC4fcnSTP3YGC
    healthcheck:
      test: "curl --fail --silent http://localhost:8181/private/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5