version: '3.8'

services:
  keycloak:
    container_name: keycloak
    build: keycloak
    restart: always
    ports:
      - "8180:8080"
#    volumes:
#      - ./keycloak/backup:/opt/keycloak/data/h2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
