services:
  keycloak:
    container_name: keycloak
    build: keycloak
    restart: unless-stopped
    ports:
      - "8180:8080"
      - "9000:9000"
    env_file:
      - keycloak.env

  keycloak-healthcheck:
    container_name: keycloak-healthcheck
    build: keycloak-healthcheck
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_ADMIN_HOST=http://keycloak:9000
      - RETRY_MAX_ATTEMPT=10
      - RETRY_WAIT_INTERVAL_SECONDS=5

  keycloak-init:
    container_name: keycloak-init
    build: keycloak-init
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    env_file:
      - keycloak.env
    environment:
      - KEYCLOAK_HOST=http://keycloak:8080

  identity-service:
    extends:
      file: docker-compose.app.yml
      service: identity-service
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    environment:
      - KEYCLOAK_URL=http://keycloak:8080