services:
  mocks:
    image: wiremock/wiremock:3.13.1
    restart: always
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/__admin/mappings" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: [ "--verbose" ]
    volumes:
      - ./mocks/mappings:/home/wiremock/mappings

  identity-service:
    extends:
      file: docker-compose.app.yml
      service: identity-service
    depends_on:
      mocks:
        condition: service_healthy
    environment:
      - KEYCLOAK_URL=http://mocks:8080