spring:
  jmx:
    enable: false
  application:
    name: identity-service

server:
  port: 8181
  servlet:
    contextPath: /identity

keycloak:
  server-url: http://localhost:8180
  realm: shopping-api
  client-id: demo-client # please never save plain text data like this in a real project
  client-secret: ZhVCiZ3pyKwxWcXh5K7wC4fcnSTP3YGC # please never save plain text data like this in a real project

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: false