server:
  port: 8181
  servlet:
    contextPath: /identity

spring:
  jmx:
    enable: false
  application:
    name: identity-service
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    time-zone: UTC

keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:groot-mg}
  client-id: ${KEYCLOAK_CLIENT_ID:groot-mg-identity-app} # please never save plain text data like this in a real project
  client-secret: ${KEYCLOAK_CLIENT_SECRET:yeL37FpucV9slQGp6r5OTmzEu485yETv} # please never save plain text data like this in a real project

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      slo:
        http.server.requests: 5ms, 25ms, 50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1000ms, 2000ms, 3000ms, 4000ms, 5000ms
        http.client.requests: 5ms, 25ms, 50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1000ms, 2000ms, 3000ms, 4000ms, 5000ms

springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /api-docs
  show-actuator: false # there is a bug on security library with actuator and gateway together
  swagger-ui:
    enabled: true
    path: /swagger