name: CI Workflow

on:
  schedule:
    - cron: '0 12 1 */1 *'
  push:
    branches: [ main ]
    paths:
      - 'gradle/**'
      - '**.gradle'
      - 'gradle.properties'
      - 'identity-app/**'
      - 'identity-ft/**'
      - '.github/workflows/ci-workflow.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'gradle/**'
      - '**.gradle'
      - 'gradle.properties'
      - 'identity-app/**'
      - 'identity-ft/**'
      - '.github/workflows/ci-workflow.yml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'groot-mg/test/identity'

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build + unit tests
        run: ./gradlew :identity-app:build

      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: |
            identity-app/build/reports/tests/test/**/*

      - name: Set repository basename
        id: set-basename
        run: echo "REPO_BASENAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: identity-app/build/libs/${{ env.REPO_BASENAME }}.jar

  docker-image:
    needs: build-and-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: identity-app/build/libs/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: identity-app/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  functional-tests:
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set repository basename
        id: set-basename
        run: echo "REPO_BASENAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ${{ env.REPO_BASENAME }}/identity-app/build/libs/

      - name: Run functional tests
        run: ./gradlew --no-daemon :identity-ft:cucumber
