name: Build and test

on:
  push:
    branches: [ main ]
    paths:
      - identity-app/**
      - identity-ft/**
  pull_request:
    branches: [ main ]
    paths:
      - identity-app/**
      - identity-ft/**
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build + unit tests
        run: ./gradlew :identity-app:build

      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: |
            identity-app/build/reports/tests/test/**/*

      - name: Set repository basename
        id: set-basename
        run: echo "REPO_BASENAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: identity-app/build/libs/${{ env.REPO_BASENAME }}.jar

  functional-tests:
    needs: build-and-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set repository basename
        id: set-basename
        run: echo "REPO_BASENAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ${{ env.REPO_BASENAME }}/identity-app/build/libs/

      - name: Run functional tests
        run: ./gradlew --no-daemon :identity-ft:cucumber
